server:
  port: 8762
spring:
  application:
    name: zuul-server
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
zuul:
  routes:
    image-resizer:
      path: /image-resizer/**
      serviceId: image-resizer